use clef;

ALTER TABLE Album MODIFY COLUMN name VARCHAR(255)
CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL;

ALTER TABLE Album MODIFY COLUMN label VARCHAR(255)
CHARACTER SET utf8 COLLATE utf8_general_ci NULL;

ALTER TABLE Track MODIFY COLUMN name VARCHAR(255)
CHARACTER SET utf8 COLLATE utf8_general_ci NULL;

ALTER TABLE Artist MODIFY COLUMN name VARCHAR(100)
CHARACTER SET utf8 COLLATE utf8_general_ci NULL;

ALTER TABLE Playlist MODIFY COLUMN name VARCHAR(100)
CHARACTER SET utf8 COLLATE utf8_general_ci NULL;
